AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_world/app.lambda_handler
      Runtime: python3.10
      CodeUri: hello_world/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:us-west-1:710271919598:table/VisitorCountTable
      Environment:
        Variables:
          TABLE_NAME: VisitorCountTable

Outputs:
  VisitorCountTableArn:
    Value: arn:aws:dynamodb:us-west-1:710271919598:table/VisitorCountTable
    Export:
      Name: VisitorCountTableArn

  ApiGatewayUrl:
    Value: https://0ootsin9k1.execute-api.us-west-1.amazonaws.com/Prod/visitor-count
    Export:
      Name: ApiGatewayUrl